### ISSUE TITLE
seshat's events.db should be encrypted

### ISSUE THREAD

**Issue by ara4n** [matrix-org/seshat#1]
having all my e2e msgs sitting unencrypted in a plaintext sqlite DB is Not Ideal

**Comment by ara4n** [comment]
actually, should we even be storing the events in the first place by default? should we just build the index but throw away the events and then pull them in for search results from the server via the /context API when needed? (or store them in their megolm-encrypted form?)

**Comment by poljar** [comment]
I'm not sure we want to change the default here to fetching events from the server, this would make the search noticeably slower. Exposing just the indexing part is fine and riotX will make use of it since it already uses a database to store all events.

As for storing the events encrypted sure, we could do that but what about the index, it's going to leak some information as well.

**Comment by ara4n** [comment]
the leaky index is inevitable. but storing e2e events in plaintext unnecessarily seems something we should avoid.

**Comment by poljar** [comment]
The leaky index might not be inevitable if we use something like this https://github.com/zboxfs/zbox (based on libsodium). 

If we do encrypt the index that way we might as well use it on the db. That would of course require storing a secret securely somewhere.

**Comment by poljar** [comment]
This has been fixed by #15.
