### ISSUE TITLE
Seshat leaks heap at about 4GB/minute

### ISSUE THREAD

**Issue by ara4n** [matrix-org/seshat#21]
According to Instruments on macOS Catalina & Electron 7.1.2, we constantly leak heap at a fairly aggressive rate (until it hit 170GB of swap and fell over).  Stack traces are:

```
   0 libsystem_malloc.dylib malloc_zone_realloc
   1 libsystem_malloc.dylib realloc
   2 index.node alloc::raw_vec::RawVec$LT$T$C$A$GT$::reserve::hcbf086340130821f
   3 index.node std::io::read_to_end::h49e3d44809861740
   4 index.node _$LT$seshat..encrypted_dir..EncryptedMmapDirectory$u20$as$u20$tantivy..directory..directory..Directory$GT$::open_read::h4ef0f5cdbc202d39
   5 index.node _$LT$tantivy..directory..managed_directory..ManagedDirectory$u20$as$u20$tantivy..directory..directory..Directory$GT$::open_read::h5e6b8286b68b214c
   6 index.node tantivy::core::segment::Segment::open_read::he0af154fc2984176
   7 index.node tantivy::core::segment_reader::SegmentReader::open::h93af06f623defaaa
   8 index.node _$LT$core..iter..adapters..ResultShunt$LT$I$C$E$GT$$u20$as$u20$core..iter..traits..iterator..Iterator$GT$::next::h04ecd362333af029
   9 index.node _$LT$alloc..vec..Vec$LT$T$GT$$u20$as$u20$alloc..vec..SpecExtend$LT$T$C$I$GT$$GT$::from_iter::ha8306f909ff50a77
  10 index.node core::iter::adapters::process_results::ha014ec417fc3cced
  11 index.node tantivy::reader::InnerIndexReader::reload::h62a6b77d6fe8cd2f
  12 index.node tantivy::reader::IndexReaderBuilder::try_into::_$u7b$$u7b$closure$u7d$$u7d$::h276908aa8db1310c
  13 index.node std::sys_common::backtrace::__rust_begin_short_backtrace::h62b87800dccf9e89
  14 index.node std::panicking::try::do_call::hc14f628e60cf3ae0 (.llvm.14178565697805299287)
  15 index.node __rust_maybe_catch_panic
  16 index.node core::ops::function::FnOnce::call_once$u7b$$u7b$vtable.shim$u7d$$u7d$::h44fc380e25c5fc46
  17 index.node _$LT$alloc..boxed..Box$LT$F$GT$$u20$as$u20$core..ops..function..FnOnce$LT$A$GT$$GT$::call_once::h968b34e75ca2d607
  18 index.node std::sys::unix::thread::Thread::new::thread_start::h41902c88eed57989
  19 libsystem_pthread.dylib _pthread_start
  20 libsystem_pthread.dylib thread_start
```

**Comment by poljar** [comment]
So I investigated it a bit further to be sure that it is our encrypted directory implementation that is to blame for this.

The below traces are done with an index containing one million events. The only difference is the first one is using the stock [MmapDirectory](https://docs.rs/tantivy/0.10.3/tantivy/directory/struct.MmapDirectory.html) while the second one is using our in-house [EncryptedMmapDirectory](https://github.com/matrix-org/seshat/blob/master/src/encrypted_dir.rs#L564).

![Stock](https://i.imgur.com/MGdDwfS.png)
The picture shows a small amount of non-mmaped allocations in the `open_read()` method. While there are a bunch of allocations, they are quite small and not worrisome.

![Encrypted](https://i.imgur.com/BZjfjkX.png)
Here we can see the same backtraces for the `EncryptedMmapDirectory`, a huge list of 64kB allocations.

The cause for such a drastic difference in memory usage is that the `open_read()` method for our `EncryptedMmapDirectory` sadly abandons mmap and instead reads and decrypts the whole file in memory.

Tantivy seems to open the whole index and heavily rely on mmap to keep memory usage in check. API limitations in Tantivy's `ReadOnlySource` sadly make it impossible to implement the decryption logic to happen on the fly, while we read data from the memory mapped file.

To solve this `ReadOnlySource` would need to provide a different API instead of the existing `[u8]` slice based one. Working with slices, while convenient, doesn't allow `Directory` implementers to modify the behavior while read operations are happening.

A `Read` + `Seek` based API could provide all the necessary functionality of the slice based API while also allowing implementers to modify the `Read` and `Seek` behavior. An easy upgrade path for the `RAMDirectory` as well as for the `MmapDirectory` exists in the form of `Cursor` which wraps slices and vectors and provides them with a `Read` and `Seek` implementation.

The existing `ReadOnlySource` API is extensively used throughout the Tantivy code-base and such a change sadly isn't trivial.
