### ISSUE TITLE
Rename seshat-node package

### ISSUE THREAD

**Issue by jryans** [matrix-org/seshat#9]
It seems a bit strange for the package on npm to be called `seshat-node`... The node bit is quite redundant, since that's why it's on npm in the first place.

Have a **directory** `seshat-node` seems fine, but it'd be nice to change the package name in `package.json` so that it feels more natural to use.

**Comment by poljar** [comment]
There is already a package on npm called `seshat`. Unless we want to scope the package somehow we can't use just `seshat`, no?

**Comment by jryans** [comment]
Hmm... I am tempted to say we should create an org and have a scoped package then. That would communicate the purpose more clearly without redundant words. I'll raise the idea and see where it takes us.

**Comment by jryans** [comment]
Alternatively, we could go with a less obscure name like `matrix-search-indexer` as @dbkr suggests.

**Comment by poljar** [comment]
Eh, I'm kinda fond of the Seshat name especially since we did get the `seshat` crate name on [crates.io](https://crates.io/crates/seshat). Can't we maybe use `matrix-seshat` on npm to differentiate it from the existing `seshat` on npm as well as remove the redundancy that's present in `seshat-node`?

**Comment by jryans** [comment]
Ah yes, `matrix-seshat` seems workable as well. 😄

**Comment by poljar** [comment]
Ok, I'll rename it to `matrix-seshat` in that case.
