### ISSUE TITLE
Electron 13

### ISSUE THREAD

**Issue by petabyteboy** [matrix-org/seshat#94]
**Is your feature request related to a problem? Please describe.**

We have updated Electron to 13.x in nixpkgs, but didn't pin the version used for element-desktop properly. Now we can't add native extensions until they build with Electron 13, since downgrading Electron might break state.

**Describe the solution you'd like**
Probably update neon to the latest release. Maybe change to N-API?

**Describe alternatives you've considered**
Patch neon? Probably would need multiple patches though.

**Additional context**
https://github.com/NixOS/nixpkgs/pull/124907

**Comment by poljar** [comment]
Updating neon is inevitable so that's the way to go, though it's a bit non-trivial since `neon-serde` seems to be abandoned, so we'll need to get rid of it and `neon` itself has a new API.

For reference, the migration guide for `neon` is found [here](https://github.com/neon-bindings/neon/blob/main/MIGRATION_GUIDE.md).

**Comment by petabyteboy** [comment]
There is a maintained-ish fork of neon_serde: https://github.com/antonok-edm/neon-serde/tree/refactor/update-neon-0.8

The whole thing is non-trivial, but I think I'm making good progress.

**Comment by poljar** [comment]
This has been addressed by #95 and #97.
