### ISSUE TITLE
npm release 2.2.4 doesn't match git

### ISSUE THREAD

**Issue by dbkr** [matrix-org/seshat#98]
The files in the 2.2.4 release on npm don't match what's in the git repo - specifically `native/Cargo.toml` is a version without the new `dependencies.neon` section. This is preventing 2.2.4's napi support / electron 13 compatibility from working because neon is still trying to build against the old API.

**Comment by poljar** [comment]
The [2.2.4](https://github.com/matrix-org/seshat/releases/tag/2.2.4) release is a couple of months old, the [CHANGELOG](https://github.com/matrix-org/seshat/blob/master/CHANGELOG.md#224---2021-03-26) also states this.

It isn't surprising that a couple of month old release doesn't match latest master.

This issue is probably asking where the release with `n-api` support is, it's coming. The main problem with this release is that we depend on a unreleased version of neon-serde: https://github.com/matrix-org/seshat/blob/c8311029dfc66a1d43f86ebb42e768f89c260fea/seshat-node/native/Cargo.toml#L19.

Since upstream for neon-serde seems to be dead, we'll have to do a forked release of it as well.

**Comment by dbkr** [comment]
Ah, so it is - maybe I was misreading 'Mar' for 'May' or something

**Comment by poljar** [comment]
This has now been addressed by the 2.3.0 release. Let me know if there are any build problems.
